/*
#Randon numbers generated by TinyOS, sending by Node-Red via 
MQTT to Thingspeak #Node red and ThingSpeak project 
#IoT course 
#A.Y 2019-2020 
#Plitecnico di Milano 
#Hiva Amiri #Erfan Abbasi zadeh #Mohammad Javad Ebrahimpour
*/
#ifndef TinyOS2NodeRed_H
#define TinyOS2NodeRed_H

typedef nx_struct _messageToSend {
        nx_uint16_t _MoteID;
        nx_uint16_t _dataMessage;

}_messageToSend_t;



enum{
    AM_MY_MSG = 6,
    _REDUCE_RANGE = 100,
    _FREQUENNCY = 5000,
};

#endif
